# Generated by Django 5.2.6 on 2025-09-06 11:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'заняття', 'verbose_name_plural': 'заняття'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курси'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'кафедра', 'verbose_name_plural': 'кафедри'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'запис', 'verbose_name_plural': 'записи'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'факультет', 'verbose_name_plural': 'факультети'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'викладач', 'verbose_name_plural': 'викладачі'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'студент', 'verbose_name_plural': 'студенти'},
        ),
        migrations.AlterField(
            model_name='class',
            name='classroom',
            field=models.CharField(max_length=50, verbose_name='аудиторія'),
        ),
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='class',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.professor', verbose_name='викладач'),
        ),
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.CharField(max_length=100, verbose_name='розклад'),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(max_length=20, verbose_name='семестр'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='кредити'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.department', verbose_name='кафедра'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.faculty', verbose_name='факультет'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='class_enrolled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.class', verbose_name='заняття'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, verbose_name='дата запису'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='оцінка'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='студент'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.department', verbose_name='кафедра'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='office',
            field=models.CharField(max_length=50, verbose_name='офіс'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(verbose_name='дата вступу'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.faculty', verbose_name='факультет'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='ID студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='назва матеріалу')),
                ('description', models.TextField(blank=True, verbose_name='опис')),
                ('file', models.FileField(upload_to='course_materials/', verbose_name='файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='дата завантаження')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.class', verbose_name='заняття')),
            ],
            options={
                'verbose_name': 'матеріал курсу',
                'verbose_name_plural': 'матеріали курсу',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Понеділок'), ('TUE', 'Вівторок'), ('WED', 'Середа'), ('THU', 'Четвер'), ('FRI', "П'ятниця"), ('SAT', 'Субота')], max_length=3, verbose_name='день тижня')),
                ('start_time', models.TimeField(verbose_name='час початку')),
                ('end_time', models.TimeField(verbose_name='час закінчення')),
                ('classroom', models.CharField(max_length=50, verbose_name='аудиторія')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='lms.class', verbose_name='заняття')),
            ],
            options={
                'verbose_name': 'розклад',
                'verbose_name_plural': 'розклади',
            },
        ),
    ]
