# Generated by Django 5.2.6 on 2025-09-06 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_class_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'verbose_name': 'Матеріал курсу', 'verbose_name_plural': 'Матеріали курсу'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.class', verbose_name='Заняття'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(upload_to='course_materials/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва матеріалу'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='lms.class'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'Понеділок'), ('TUE', 'Вівторок'), ('WED', 'Середа'), ('THU', 'Четвер'), ('FRI', "П'ятниця"), ('SAT', 'Субота')], max_length=3),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
