# Generated by Django 5.2.6 on 2025-09-24 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_coursematerial_options_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'розклад', 'verbose_name_plural': 'розклади'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='lms.class', verbose_name='заняття'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.CharField(max_length=50, verbose_name='аудиторія'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'Понеділок'), ('TUE', 'Вівторок'), ('WED', 'Середа'), ('THU', 'Четвер'), ('FRI', "П'ятниця"), ('SAT', 'Субота')], max_length=3, verbose_name='день тижня'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(verbose_name='час закінчення'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='час початку'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва завдання')),
                ('description', models.TextField(verbose_name='Опис завдання')),
                ('assignment_type', models.CharField(choices=[('LAB', 'Лабораторна робота'), ('HW', 'Домашнє завдання'), ('PROJECT', 'Проект'), ('ESSAY', 'Ессе')], default='LAB', max_length=10, verbose_name='Тип завдання')),
                ('due_date', models.DateTimeField(verbose_name='Термін здачі')),
                ('max_points', models.IntegerField(default=100, verbose_name='Максимальний бал')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.class', verbose_name='Заняття')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
            },
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_submissions/', verbose_name='Файл роботи')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата здачі')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар студента')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Оцінка')),
                ('teacher_feedback', models.TextField(blank=True, verbose_name='Відгук викладача')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оцінювання')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.assignment', verbose_name='Завдання')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Робота студента',
                'verbose_name_plural': 'Роботи студентів',
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
