# Generated by Django 5.2.6 on 2025-10-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_schedule_options_alter_schedule_class_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Файл завдання'),
        ),
    ]
